project:
  type: website
  output-dir: docs

website:

  title: "Immunoinformatics visualizations"
  
  navbar:
    # background: "#cfe1ed"
    left:
      - href: index.qmd
        text: Welcome
      - text: Repertoire-level exploration
        menu:
          - text: Gene usage
            href: qmd/gene_repertoire.qmd
          - text: Diversity estimation
            href: qmd/diversity.qmd
          - text: Clonality
          - text: Public Clonotypes
      - text: Clonotype-level exploration
        menu: 
          - text: Clonotype evolution
          - text: Motif visualization
      - text: Color paletters
        href: qmd/color_palette.qmd
        
    right: 
      - icon: github
        href: https://github.com/NatAnastas/immunovisual

  page-footer: 
    border: true
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    right: "[License](https://github.com/NatAnastas/immunovisual/blob/main/LICENSE)"

editor: source

format:
  html:
    theme: [morph, sass/theme-light.scss]
    fig-format: svg
    code-fold: true
    code-block-border-left: "#5f646a"