project:
  type: website
  output-dir: docs

website:

  title: "Immunoinformatics visualizations"

  navbar:
    # background: "#cfe1ed"
    left:
      - href: index.qmd
        text: Welcome
      - text: Repertoire-level exploration
        menu:
          - text: Clonality
            href: qmd/public_clonotypes.qmd
          - text: Diversity estimation
            href: qmd/diversity.qmd
          - text: Gene repertoire
            href: qmd/gene_repertoire.qmd
          - text: V(D)J recombination
            href: qmd/V(D)J_recombination.qmd
      - text: Clonotype-level exploration
        menu: 
          - text: Clonotype evolution
            href: qmd/clonotype_evolution.qmd           
          - text: Motif visualization
            href: qmd/motif_visualization.qmd           
      - text: RNAseq
        menu:
          - text: Bubble plot
            href: qmd/bubble_plot.qmd
          - text: Heatmap
            href: qmd/heatmap.qmd 
          - text: Pathway diagram
            href: qmd/pathway_diagram.qmd
          - text: PCA
            href: qmd/PCA.qmd
          - text: Volcano plots
            href: qmd/volcano_plot.qmd
      - text: Color paletters
        href: qmd/color_palette.qmd
        
    right: 
      - icon: github
        href: https://github.com/NatAnastas/immunovisual
        

  page-footer: 
    border: true
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    right: "[License](https://github.com/NatAnastas/immunovisual/blob/main/LICENSE)"

editor: source

format:
  html:
    theme: [morph, sass/theme-light.scss]
    fig-format: svg
    toc: true
    code-fold: true
    code-block-border-left: "#5f646a"
knitr:
 opts_chunk:
   dev: svg
   dev.args: { bg: "transparent" }
    