project:
  type: website
  output-dir: docs

# css:
#     - styles.css

website:

  title: "Immunoinformatics visualizations"
  
  navbar:
    background: "#cfe1ed"
    left:
      - href: index.qmd
        text: Overview
      - href: diversity.qmd
        text: Diversity estimation
      - href: gene_repertoire.qmd
        text: Gene repertoire
      - href: color_palette.qmd
        text: Color palettes
    right: 
      - icon: github
        href: https://github.com/NatAnastas/immunovisual

  page-footer: 
    border: true
    left: "Author **Natasa Anastasiadou**"
    right: "This page is built with [Quarto](https://quarto.org/)"



      # right: "This page is built with Quarto."



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: "#5184a7"

    
    

editor: source

