project:
  type: website

website:
  # title: "Immunoinformatics visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: diversity.qmd
        text: Diversity
      - href: gene_repertoire.qmd
        text: Gene repertoire
      - href: color_palette.qmd
        text: Color palettes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

