project:
  type: website

website:
  # title: "Immunoinformatics visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: diversity.qmd
        text: Diversity
      - color_palette.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

